import React from 'react';
import { Shield, ArrowLeft } from 'lucide-react';
import { Button } from '../components/ui/button';

export const Terms = ({ onBack }: { onBack: () => void }) => {
    return (
        <div className="min-h-screen bg-slate-50 dark:bg-slate-900 py-12 px-4 sm:px-6 lg:px-8">
            <div className="max-w-4xl mx-auto bg-white dark:bg-slate-800 rounded-lg shadow-xl overflow-hidden border border-slate-200 dark:border-slate-700">
                <div className="bg-slate-900 px-6 py-4 flex items-center justify-between">
                    <div className="flex items-center gap-3">
                        <Shield className="w-6 h-6 text-blue-400" />
                        <h1 className="text-xl font-bold text-white">Terms of Service</h1>
                    </div>
                    <Button variant="ghost" size="sm" onClick={onBack} className="text-slate-300 hover:text-white hover:bg-slate-800">
                        <ArrowLeft className="w-4 h-4 mr-2" />
                        Back
                    </Button>
                </div>

                <div className="p-8 prose prose-slate dark:prose-invert max-w-none">
                    <p className="text-sm text-muted-foreground mb-6">Last Updated: December 25, 2025</p>

                    <section className="mb-8">
                        <h2 className="text-2xl font-semibold mb-4 text-slate-900 dark:text-white">1. Acceptance of Terms</h2>
                        <p className="text-slate-600 dark:text-slate-300">
                            By accessing or using 2t1 – Personal Finance Manager ("the App"), you agree to be bound by these Terms of Service. If you do not agree, do not use the App.
                        </p>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-2xl font-semibold mb-4 text-slate-900 dark:text-white">2. Service Description</h2>
                        <p className="text-slate-600 dark:text-slate-300">
                            2t1 is a tool designed to help users track and manage their personal finances. We provide data visualization and management features based on user-provided information.
                        </p>
                    </section>

                    <section className="mb-8 p-6 bg-amber-50 dark:bg-amber-900/20 rounded-lg border border-amber-200 dark:border-amber-800">
                        <h2 className="text-2xl font-semibold mb-4 text-amber-900 dark:text-amber-100">3. "As-Is" and "No Guarantee" Clause</h2>
                        <ul className="list-disc pl-6 space-y-2 text-slate-700 dark:text-slate-300">
                            <li><strong>No Warranty:</strong> The App is provided on an "AS IS" and "AS AVAILABLE" basis.</li>
                            <li><strong>No Financial Advice:</strong> 2t1 is a data management tool, not a financial advisor. Any information provided within the App does not constitute professional financial, investment, or legal advice.</li>
                            <li><strong>No Guarantee of Accuracy:</strong> We do not guarantee the accuracy, completeness, or reliability of any data generated by the App. Use of the App is at your own risk.</li>
                            <li><strong>Limitation of Liability:</strong> In no event shall 2t1, its developers, or affiliates be liable for any financial losses, data loss, or damages arising from the use or inability to use the App.</li>
                        </ul>
                    </section>

                    <section className="mb-8">
                        <h2 className="text-2xl font-semibold mb-4 text-slate-900 dark:text-white">4. User Responsibilities</h2>
                        <p className="text-slate-600 dark:text-slate-300">
                            Users are responsible for the accuracy of the data they input and for maintaining the security of their Google OAuth credentials used to access the App.
                        </p>
                    </section>

                    <section className="mb-8 p-4 bg-slate-100 dark:bg-slate-700/50 rounded-lg">
                        <h2 className="text-2xl font-semibold mb-2 text-slate-900 dark:text-white">5. Governing Law</h2>
                        <p className="text-slate-600 dark:text-slate-300">
                            These terms are governed by the laws of India, with jurisdiction in <strong>Bangalore, Karnataka</strong>.
                        </p>
                    </section>
                </div>
            </div>
        </div>
    );
};
